set-option -g default-shell /bin/bash
set -g default-terminal "screen-256color"

# navigate panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# navigate windows
bind C-h previous-window
bind C-l next-window

# splitting the window
bind - split-window -v
bind | split-window -h

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2
